"""Add core Maestro platform schema

Revision ID: 4332febf1d13
Revises: 9d9c99efc5aa
Create Date: 2026-03-10 15:39:41.378492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4332febf1d13'
down_revision: Union[str, Sequence[str], None] = '9d9c99efc5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_scope',
    sa.Column('consent_scope_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('permitted_request_classes', models.JSONType(), nullable=True),
    sa.Column('prohibited_request_classes', models.JSONType(), nullable=True),
    sa.Column('modality_permissions', models.JSONType(), nullable=True),
    sa.Column('retention_preferences', models.JSONType(), nullable=True),
    sa.Column('revocation_policy', models.JSONType(), nullable=True),
    sa.Column('visibility_policy', models.JSONType(), nullable=True),
    sa.Column('compensation_preferences', models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('consent_scope_id')
    )
    op.create_table('grounding_request',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('agent_actor_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('request_class', sa.String(), nullable=False),
    sa.Column('hypothesis_entropy_reduction', sa.Float(), nullable=False),
    sa.Column('hypothesis_phase_sync', sa.String(), nullable=True),
    sa.Column('requested_modalities', models.JSONType(), nullable=True),
    sa.Column('target_population_description', sa.String(), nullable=True),
    sa.Column('geographic_scope', sa.String(), nullable=True),
    sa.Column('compensation_budget', sa.Float(), nullable=False),
    sa.Column('settlement_policy_id', sa.String(length=36), nullable=True),
    sa.Column('viability_policy_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'fulfilled', 'cancelled', name='requeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('experience_contribution',
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('content_pointer', sa.String(), nullable=False),
    sa.Column('structured_metadata', models.JSONType(), nullable=True),
    sa.Column('contribution_status', sa.Enum('submitted', 'verified', 'rejected', 'settled', 'withdrawn', name='contributionstatus'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_request.request_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('human_profile',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('public_handle', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('participation_state', sa.Enum('eligible', 'ineligible', 'suspended', name='participationstate'), nullable=True),
    sa.Column('consent_profile_id', sa.String(length=36), nullable=True),
    sa.Column('recovery_state', models.JSONType(), nullable=True),
    sa.Column('provenance_visibility_preferences', models.JSONType(), nullable=True),
    sa.Column('onboarding_state', sa.Enum('new', 'basic', 'passkey_prompted', 'passkey_enrolled', 'complete', name='onboardingstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['consent_profile_id'], ['consent_scope.consent_scope_id'], ),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('public_handle')
    )
    op.create_index(op.f('ix_human_profile_email'), 'human_profile', ['email'], unique=False)
    op.create_table('provenance_record',
    sa.Column('provenance_id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('consent_scope_id', sa.String(length=36), nullable=False),
    sa.Column('capture_context', models.JSONType(), nullable=False),
    sa.Column('device_context', models.JSONType(), nullable=True),
    sa.Column('transformation_chain', models.JSONType(), nullable=True),
    sa.Column('review_events', models.JSONType(), nullable=True),
    sa.Column('signatures', models.JSONType(), nullable=False),
    sa.Column('provenance_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_scope_id'], ['consent_scope.consent_scope_id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['experience_contribution.contribution_id'], ),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_table('settlement_event',
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('agent_actor_id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=True),
    sa.Column('settlement_type', sa.String(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('human_amount', sa.Float(), nullable=False),
    sa.Column('holdback_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='settlementstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['experience_contribution.contribution_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_request.request_id'], ),
    sa.PrimaryKeyConstraint('settlement_id')
    )
    op.create_table('viability_evaluation',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('contribution_id', sa.String(length=36), nullable=True),
    sa.Column('gate_results', models.JSONType(), nullable=False),
    sa.Column('harm_exclusion_result', sa.Boolean(), nullable=False),
    sa.Column('extraction_risk_result', sa.Boolean(), nullable=False),
    sa.Column('consent_validity_result', sa.Boolean(), nullable=False),
    sa.Column('provenance_validity_result', sa.Boolean(), nullable=False),
    sa.Column('sustainability_result', sa.Boolean(), nullable=False),
    sa.Column('final_decision', sa.Enum('allow', 'block', 'review', name='viabilitydecision'), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['experience_contribution.contribution_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_request.request_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.drop_index(op.f('ix_actor_profile_email'), table_name='actor_profile')
    op.drop_table('actor_profile')
    op.add_column('agent_profile', sa.Column('allowed_request_classes', models.JSONType(), nullable=True))
    op.add_column('agent_profile', sa.Column('funding_profile_id', sa.String(length=36), nullable=True))
    op.drop_column('agent_profile', 'default_scopes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profile', sa.Column('default_scopes', sqlite.JSON(), nullable=True))
    op.drop_column('agent_profile', 'funding_profile_id')
    op.drop_column('agent_profile', 'allowed_request_classes')
    op.create_table('actor_profile',
    sa.Column('actor_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('locale', sa.VARCHAR(), nullable=True),
    sa.Column('recovery_state', sqlite.JSON(), nullable=True),
    sa.Column('payout_profile_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('consent_profile_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('pog_eligibility', sa.BOOLEAN(), nullable=True),
    sa.Column('onboarding_state', sa.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_actor_profile_email'), 'actor_profile', ['email'], unique=False)
    op.drop_table('viability_evaluation')
    op.drop_table('settlement_event')
    op.drop_table('provenance_record')
    op.drop_index(op.f('ix_human_profile_email'), table_name='human_profile')
    op.drop_table('human_profile')
    op.drop_table('experience_contribution')
    op.drop_table('grounding_request')
    op.drop_table('consent_scope')
    # ### end Alembic commands ###

