"""Initial authentication schema

Revision ID: 9d9c99efc5aa
Revises: 
Create Date: 2026-03-10 14:23:19.204346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision: str = '9d9c99efc5aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'agent', 'org_service', name='actortype'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('primary_handle', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'suspended', 'deleted', name='actorstatus'), nullable=True),
    sa.Column('assurance_level', sa.Enum('aal1', 'aal2', 'aal3', name='assurancelevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('primary_handle')
    )
    op.create_index(op.f('ix_actor_actor_type'), 'actor', ['actor_type'], unique=False)
    op.create_index(op.f('ix_actor_status'), 'actor', ['status'], unique=False)
    op.create_table('actor_merge_audit',
    sa.Column('merge_id', sa.String(length=36), nullable=False),
    sa.Column('source_actor_id', sa.String(length=36), nullable=False),
    sa.Column('target_actor_id', sa.String(length=36), nullable=False),
    sa.Column('merge_reason', sa.String(), nullable=False),
    sa.Column('approved_by_actor_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('merge_id')
    )
    op.create_table('auth_event',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('binding_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('login_success', 'login_failure', 'magic_link_sent', 'magic_link_consumed', 'passkey_registered', 'passkey_login', 'provider_link_started', 'provider_link_completed', 'provider_link_failed', 'provider_unlinked', 'recovery_started', 'recovery_completed', 'agent_registered', 'token_issued', name='autheventtype'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('metadata_json', models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_auth_event_actor_id'), 'auth_event', ['actor_id'], unique=False)
    op.create_table('actor_profile',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('recovery_state', models.JSONType(), nullable=True),
    sa.Column('payout_profile_id', sa.String(length=36), nullable=True),
    sa.Column('consent_profile_id', sa.String(length=36), nullable=True),
    sa.Column('pog_eligibility', sa.Boolean(), nullable=True),
    sa.Column('onboarding_state', sa.Enum('new', 'basic', 'passkey_prompted', 'passkey_enrolled', 'complete', name='onboardingstate'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_actor_profile_email'), 'actor_profile', ['email'], unique=False)
    op.create_table('agent_profile',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('software_name', sa.String(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('operator_actor_id', sa.String(length=36), nullable=True),
    sa.Column('trust_tier', sa.Enum('sandbox', 'basic', 'verified', 'elevated', name='trusttier'), nullable=True),
    sa.Column('default_scopes', models.JSONType(), nullable=True),
    sa.Column('jwks_uri', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['operator_actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('credential_binding',
    sa.Column('binding_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.Enum('Maestro_local', 'passkey', 'email_link', 'oauth_oidc', 'saml', 'api_key', 'client_credentials', 'private_key_jwt', 'wallet_sig', name='providertype'), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('external_subject', sa.String(), nullable=True),
    sa.Column('external_email', sa.String(), nullable=True),
    sa.Column('external_username', sa.String(), nullable=True),
    sa.Column('public_key_thumbprint', sa.String(), nullable=True),
    sa.Column('credential_label', sa.String(), nullable=True),
    sa.Column('metadata_json', models.JSONType(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_index(op.f('ix_credential_binding_actor_id'), 'credential_binding', ['actor_id'], unique=False)
    op.create_index(op.f('ix_credential_binding_external_email'), 'credential_binding', ['external_email'], unique=False)
    op.create_index(op.f('ix_credential_binding_last_used_at'), 'credential_binding', ['last_used_at'], unique=False)
    op.create_table('provider_link_token',
    sa.Column('link_token_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.PrimaryKeyConstraint('link_token_id'),
    sa.UniqueConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_link_token')
    op.drop_index(op.f('ix_credential_binding_last_used_at'), table_name='credential_binding')
    op.drop_index(op.f('ix_credential_binding_external_email'), table_name='credential_binding')
    op.drop_index(op.f('ix_credential_binding_actor_id'), table_name='credential_binding')
    op.drop_table('credential_binding')
    op.drop_table('agent_profile')
    op.drop_index(op.f('ix_actor_profile_email'), table_name='actor_profile')
    op.drop_table('actor_profile')
    op.drop_index(op.f('ix_auth_event_actor_id'), table_name='auth_event')
    op.drop_table('auth_event')
    op.drop_table('actor_merge_audit')
    op.drop_index(op.f('ix_actor_status'), table_name='actor')
    op.drop_index(op.f('ix_actor_actor_type'), table_name='actor')
    op.drop_table('actor')
    # ### end Alembic commands ###

