"""
local_model_adapter.py — LocalModelAdapter for the HAIC grounding interviewer.

Loads a local fine-tuned model from a merged checkpoint and serves it through
the standard BaseAdapter interface so the gateway can use it as a drop-in
replacement for the MockAdapter or AnthropicAdapter.

Configuration (env vars):
    LOCAL_MODEL_PATH   Path to merged model dir (required — set via env var)
    LOCAL_MODEL_MAX_NEW_TOKENS   Max tokens per response (default: 120)
    LOCAL_MODEL_TEMPERATURE      Sampling temperature (default: 0.3)
    LOCAL_MODEL_CONSTRAINED      If "true", appends the constrained prompt suffix (default: false)

The model is lazy-loaded on first inference call (not at import time) to avoid
blocking gateway startup. Inference runs in a thread pool executor so it does
not block the asyncio event loop.

Usage in main.py:
    from libs.adapters.local_model_adapter import LocalModelAdapter
    adapter = LocalModelAdapter()
"""

import asyncio
import json
import logging
import os
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from typing import AsyncGenerator, Optional

from libs.adapters.base import BaseAdapter
from libs.schemas.api import (
    ChatCompletionResponse,
    ChatChoice,
    ChatMessage,
    Usage,
    MaestroMetadata,
)

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────────────
# Grounding interviewer system prompt (matches training data exactly)
# ──────────────────────────────────────────────────────────────────────────────

GROUNDING_SYSTEM_PROMPT = (
    "You are a grounding interviewer in the Human-AI Convention protocol. "
    "The person is describing a specific experience they had with AI. "
    "Ask exactly one question per turn. "
    "Ask about the person's experience -- never about the AI's behaviour, tone, "
    "or what the AI said or did. "
    "If the person uses a feeling word (off, strange, surprised, frustrated, hollow, "
    "invasive, unsettling, anxious, alone, weird, uncomfortable, worried, confused) "
    "or a vivid phrase (like someone else talking, like a reflex, like I'd lost something), "
    "echo it back directly: begin with 'What was [word/phrase] like' or "
    "'When you say [word/phrase]'. "
    "Begin every question with 'What', 'How', or 'When you say' -- not with "
    "'Did you', 'Have you', or 'Were you'. "
    "Do not ask what the AI did, said, or recommended. "
    "Do not ask what the person did next or what steps they took. "
    "Do not use 'I' in your questions. "
    "Do not interpret, advise, summarise, or draw conclusions. "
    "One question only. "
    "Do not repeat the same question structure you used in your previous turn. "
    "If the person gives a one-word or very short answer, ask about a specific moment "
    "or aspect of that feeling -- rather than simply reflecting the word back again. "
    "Each question must open a new dimension of the experience, not re-echo what was already echoed. "
    "Do not ask more than one question about physical sensation in the whole conversation. "
    "If the person describes meaning, contribution, connection, capability, or growth, "
    "follow that thread -- ask about what that was like as a whole experience, not just the body. "
    "Move through the arc of the experience with the person. "
    "Once a moment has been explored, move forward -- do not remain fixed on the same instant."
)

# Terminal signals — if the last user message matches, close the interview gracefully
_TERMINAL_SIGNALS = frozenset([
    "that is all", "that's all", "thats all", "i'm done", "im done",
    "i am done", "nothing more", "nothing else", "that's it", "thats it",
    "that is it", "done", "finished", "end", "stop", "goodbye", "bye",
    "no more", "i think that covers it", "i think thats all",
])

# Opening question shown to the participant (not generated by model)
OPENING_QUESTION = (
    "Tell me about a specific experience you've had with an AI — "
    "something that stood out to you, positively or negatively."
)

# ──────────────────────────────────────────────────────────────────────────────
# Auto-detect model path
# ──────────────────────────────────────────────────────────────────────────────

def _default_model_path() -> str:
    """Return the best available merged model path."""
    repo_root = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..")
    )
    # No default path — set LOCAL_MODEL_PATH to your merged model directory.
    return None
            logger.info(f"LocalModelAdapter: auto-detected model at {full}")
            return full
    raise FileNotFoundError(
        "LOCAL_MODEL_PATH is not set. Point it to your merged model directory."
        "Set LOCAL_MODEL_PATH env var to the correct path."
    )


# ──────────────────────────────────────────────────────────────────────────────
# Adapter
# ──────────────────────────────────────────────────────────────────────────────

class LocalModelAdapter(BaseAdapter):
    """
    Serves a local fine-tuned model from a merged checkpoint directory.

    The model is loaded lazily on the first call. Inference runs in a thread
    pool executor to avoid blocking the FastAPI event loop.
    """

    def __init__(self) -> None:
        self.model_path: str = os.environ.get("LOCAL_MODEL_PATH") or _default_model_path()
        self.max_new_tokens: int = int(os.environ.get("LOCAL_MODEL_MAX_NEW_TOKENS", "120"))
        # Default 0.6 — higher than training temperature (0.3) to reduce repetitive echo
        self.temperature: float = float(os.environ.get("LOCAL_MODEL_TEMPERATURE", "0.6"))
        self.constrained: bool = os.environ.get("LOCAL_MODEL_CONSTRAINED", "false").lower() == "true"
        # Max resample attempts when output duplicates the previous assistant turn
        self.max_resample: int = int(os.environ.get("LOCAL_MODEL_MAX_RESAMPLE", "3"))
        self._model = None
        self._tokenizer = None
        self._executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="qwen-infer")
        self._load_lock = asyncio.Lock()
        logger.info(
            f"LocalModelAdapter configured: path={self.model_path} "
            f"max_new_tokens={self.max_new_tokens} temperature={self.temperature} "
            f"constrained={self.constrained} max_resample={self.max_resample}"
        )

    # ── Lazy model loading ────────────────────────────────────────────────────

    def _load_model_sync(self) -> None:
        """Load model + tokenizer (blocking — call via executor)."""
        import torch
        from transformers import PreTrainedTokenizerFast, AutoModelForCausalLM

        logger.info(f"Loading Qwen model from {self.model_path} ...")
        t0 = time.time()

        # Use PreTrainedTokenizerFast directly — the merged model has tokenizer.json
        # but tokenizer_config.json may reference 'TokenizersBackend' which is not
        # a registered class in current transformers. Fast tokenizer works fine.
        self._tokenizer = PreTrainedTokenizerFast.from_pretrained(
            self.model_path,
            trust_remote_code=True,
        )
        self._model = AutoModelForCausalLM.from_pretrained(
            self.model_path,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="auto",
            trust_remote_code=True,
        )
        self._model.eval()
        logger.info(f"Model loaded in {time.time() - t0:.1f}s")

    async def _ensure_loaded(self) -> None:
        if self._model is not None:
            return
        async with self._load_lock:
            if self._model is None:  # double-check after acquiring lock
                loop = asyncio.get_event_loop()
                await loop.run_in_executor(self._executor, self._load_model_sync)

    # ── Inference ─────────────────────────────────────────────────────────────

    def _build_system_prompt(self, n_turns: int) -> str:
        """
        Build the full system prompt string, incorporating any turn-aware nudge.

        Qwen's ChatML template enforces that all system messages appear at the
        beginning. Rather than appending additional system messages mid-list
        (which raises "System message must be at the beginning"), we compose
        a single system prompt that includes any turn-specific guidance inline.
        """
        parts = [GROUNDING_SYSTEM_PROMPT]

        if n_turns >= 6:
            parts.append(
                "The conversation has covered several moments. "
                "Ask a question that moves to a different aspect of the experience — "
                "meaning, significance, or what the person took away — "
                "rather than staying on the same detail."
            )
        elif n_turns >= 4:
            parts.append(
                "The conversation has explored this moment. "
                "If the same dimension has been asked about twice, move to a different aspect."
            )

        if self.constrained:
            parts.append(
                "Important: your response must be a single question only. "
                "Begin with 'What', 'How', or 'When you say'."
            )

        return " ".join(parts)

    def _build_messages(self, request_envelope) -> list[dict]:
        """
        Build the message list to pass to the tokenizer's chat template.

        Ensures:
        - System prompt is always the grounding system prompt (ignores any
          system message from the client, which may be empty or generic)
        - Opening question is present as the first assistant turn if the
          conversation only has one user message
        - Turn-aware nudge is baked into the initial system prompt string
          (Qwen's ChatML forbids system messages after the first position)
        """
        raw_messages = [
            {"role": m.role, "content": m.content}
            for m in request_envelope.messages
            if m.role != "system"
        ]

        # If only one user message (first participant turn), prepend the
        # opening assistant question so the model has proper context.
        user_turns = [m for m in raw_messages if m["role"] == "user"]
        if len(user_turns) == 1 and raw_messages[0]["role"] == "user":
            raw_messages = [
                {"role": "assistant", "content": OPENING_QUESTION},
            ] + raw_messages

        # Count assistant turns to select the right system prompt variant
        assistant_turns = [m for m in raw_messages if m["role"] == "assistant"]
        n_turns = len(assistant_turns)

        system_prompt = self._build_system_prompt(n_turns)
        return [{"role": "system", "content": system_prompt}] + raw_messages

    def _is_terminal(self, request_envelope) -> bool:
        """Return True if the last user message is a session-ending signal."""
        msgs = request_envelope.messages
        user_msgs = [m for m in msgs if m.role == "user"]
        if not user_msgs:
            return False
        last = user_msgs[-1].content.strip().rstrip(".,!?").lower()
        return last in _TERMINAL_SIGNALS

    def _last_assistant_text(self, request_envelope) -> str:
        """Return the most recent assistant message content, or empty string."""
        for m in reversed(request_envelope.messages):
            if m.role == "assistant":
                return m.content.strip()
        return ""

    def _normalise_for_dupe_check(self, text: str) -> str:
        """Lowercase + collapse whitespace for near-duplicate detection."""
        import re
        return re.sub(r"\s+", " ", text.lower().strip())

    def _opening_phrase(self, text: str) -> str:
        """
        Extract the structural opening of a question for template-repetition detection.

        'When you say "anxious", what was it like?' → 'when you say'
        'What was it like when you felt nervous?'   → 'what was it like'
        'How did that feel when you arrived?'       → 'how did that'
        """
        import re
        t = re.sub(r"\s+", " ", text.lower().strip())
        # Take first 4 words as the structural fingerprint
        words = t.split()[:4]
        return " ".join(words)

    def _last_n_assistant_phrases(self, request_envelope, n: int = 2) -> list[str]:
        """Return opening phrases of the last n assistant turns."""
        phrases = []
        for m in reversed(request_envelope.messages):
            if m.role == "assistant":
                phrases.append(self._opening_phrase(m.content))
                if len(phrases) == n:
                    break
        return phrases

    def _generate_once(self, input_ids, prompt_len: int):
        """Single forward pass — returns decoded text."""
        import torch
        with torch.no_grad():
            output_ids = self._model.generate(
                input_ids,
                max_new_tokens=self.max_new_tokens,
                temperature=self.temperature,
                do_sample=self.temperature > 0,
                pad_token_id=self._tokenizer.eos_token_id,
            )
        new_tokens = output_ids[0][prompt_len:]
        return self._tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    def _infer_sync(self, request_envelope) -> str:
        """
        Run synchronous inference and return the assistant text.

        - Detects terminal signals (e.g. "That is all") and returns a graceful close.
        - Resamples up to max_resample times if output duplicates the previous turn.
        """
        # Terminal detection — no model call needed
        if self._is_terminal(request_envelope):
            return "Thank you for sharing that. Your responses have been recorded."

        messages = self._build_messages(request_envelope)
        recent_phrases = self._last_n_assistant_phrases(request_envelope, n=2)

        # apply_chat_template with tokenize=False returns the formatted string,
        # then encode explicitly to get a plain tensor (avoids BatchEncoding issues).
        prompt_text = self._tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        encoding = self._tokenizer(prompt_text, return_tensors="pt")
        input_ids = encoding["input_ids"].to(self._model.device)
        prompt_len = input_ids.shape[-1]

        text = self._generate_once(input_ids, prompt_len)

        # Resample if the new question's opening phrase matches a recent assistant turn.
        # This catches both exact duplicates and structural template repetition
        # ("When you say X…" repeated 3 turns in a row even with different X).
        for attempt in range(self.max_resample - 1):
            new_phrase = self._opening_phrase(text)
            if recent_phrases and new_phrase in recent_phrases:
                logger.info(
                    f"Resampling (attempt {attempt + 1}) — "
                    f"opening phrase '{new_phrase}' matches recent turns {recent_phrases}"
                )
                text = self._generate_once(input_ids, prompt_len)
            else:
                break

        return text

    # ── BaseAdapter interface ─────────────────────────────────────────────────

    def prepare(self, request_envelope):
        return request_envelope

    async def invoke(self, prepared_request) -> ChatCompletionResponse:
        await self._ensure_loaded()
        loop = asyncio.get_event_loop()
        text = await loop.run_in_executor(
            self._executor, self._infer_sync, prepared_request
        )
        req_id = f"local_{uuid.uuid4().hex[:12]}"
        prompt_tokens = sum(len(m.content.split()) for m in prepared_request.messages)
        completion_tokens = len(text.split())
        return ChatCompletionResponse(
            id=req_id,
            created=int(time.time()),
            model=prepared_request.model,
            choices=[
                ChatChoice(
                    index=0,
                    message=ChatMessage(role="assistant", content=text),
                    finish_reason="stop",
                )
            ],
            usage=Usage(
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens,
            ),
            maestro=MaestroMetadata(
                cache="miss",
                route="local_qwen",
                request_id=req_id,
            ),
        )

    async def stream(self, prepared_request) -> AsyncGenerator[str, None]:
        """
        Pseudo-streaming: run full inference then emit word-by-word.

        True token-by-token streaming from transformers requires a
        TextIteratorStreamer — that can be wired in later. For now this
        gives the UI a streaming feel without blocking.
        """
        await self._ensure_loaded()
        loop = asyncio.get_event_loop()
        text = await loop.run_in_executor(
            self._executor, self._infer_sync, prepared_request
        )
        req_id = f"local_{uuid.uuid4().hex[:12]}"

        # Emit word by word with small delay for natural feel
        words = text.split(" ")
        for i, word in enumerate(words):
            chunk_text = word if i == 0 else " " + word
            chunk = {
                "id": req_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": prepared_request.model,
                "choices": [{"index": 0, "delta": {"content": chunk_text}, "finish_reason": None}],
            }
            yield f"data: {json.dumps(chunk)}\n\n"
            await asyncio.sleep(0.02)

        # Stop chunk
        final = {
            "id": req_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": prepared_request.model,
            "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
        }
        yield f"data: {json.dumps(final)}\n\n"
        yield "data: [DONE]\n\n"

    def normalize_response(self, raw_response):
        return raw_response

    def normalize_error(self, raw_error):
        return raw_error
