"""initial_schema

Revision ID: 599f0a63e444
Revises: 
Create Date: 2026-03-17 17:31:41.285470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599f0a63e444'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.Enum('human', 'agent', name='actortype'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('actor_created', 'consent_updated', 'request_created', 'request_evaluated', 'contribution_submitted', 'contribution_evaluated', 'settlement_attempted', 'revocation_requested', 'revocation_completed', 'operator_decision', name='auditeventtype'), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', app.models.domain.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('hypothesis_or_goal', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('model_or_agent_version', sa.String(), nullable=True),
    sa.Column('result_classification', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', 'settlement_pending', 'settled', 'rolled_back', name='learningrunstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viability_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('overall_viability', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('allow', 'block', 'review', name='viabilitydecision'), nullable=False),
    sa.Column('gates_evaluated', app.models.domain.JSONType(), nullable=False),
    sa.Column('decision_rationale', sa.String(), nullable=True),
    sa.Column('evaluation_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('target_ref', sa.String(length=36), nullable=False),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('approval_scope', sa.String(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'conditionally_approved', name='approvaldecisionenum'), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('conditions', app.models.domain.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['learning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('allowed_axes', app.models.domain.JSONType(), nullable=True),
    sa.Column('max_task_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('privacy_level', sa.Enum('standard', 'high', 'maximum', name='privacylevel'), nullable=True),
    sa.Column('allow_model_training', sa.Boolean(), nullable=True),
    sa.Column('allow_public_aggregate', sa.Boolean(), nullable=True),
    sa.Column('min_hourly_equivalent_usd', sa.Float(), nullable=True),
    sa.Column('payout_threshold_usd', sa.Float(), nullable=True),
    sa.Column('payout_method', sa.Enum('crypto', 'fiat', 'credit', name='payoutmethod'), nullable=True),
    sa.Column('daily_max_contributions', sa.Integer(), nullable=True),
    sa.Column('weekly_max_hours', sa.Integer(), nullable=True),
    sa.Column('require_full_provenance', sa.Boolean(), nullable=True),
    sa.Column('revocation_window_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id')
    )
    op.create_table('grounding_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lived_experience_axis', sa.Enum('causal_reasoning', 'context_anchoring', 'ethical_deliberation', 'interpretability_provenance', 'long_horizon_planning', 'playful_creativity', name='livedexperienceaxis'), nullable=False),
    sa.Column('requested_modality', sa.String(), nullable=False),
    sa.Column('protocol_instructions', sa.String(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('compensation_amount', sa.Float(), nullable=False),
    sa.Column('effective_hourly_estimate', sa.Float(), nullable=False),
    sa.Column('entropy_reduction_hypothesis', sa.String(), nullable=False),
    sa.Column('phase_synchronization_hypothesis', sa.String(), nullable=False),
    sa.Column('evidence_artifact_description', sa.String(), nullable=False),
    sa.Column('contributions_required', sa.Integer(), nullable=True),
    sa.Column('viability_policy_snapshot', app.models.domain.JSONType(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_viability', 'open', 'in_progress', 'review', 'settled', 'cancelled', name='requeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('assumptions', app.models.domain.JSONType(), nullable=True),
    sa.Column('steps', app.models.domain.JSONType(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'active', 'completed', 'failed', 'revoked', name='planstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['learning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('evidence_links', app.models.domain.JSONType(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('target_ref', sa.String(length=36), nullable=True),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('claim_text', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=True),
    sa.Column('lane', sa.Enum('empirical', 'theory', 'literature', name='lanetype'), nullable=False),
    sa.Column('verdict', sa.Enum('verified', 'partially_verified', 'unresolved', 'contradicted', 'metaphorical_or_nonliteral', 'not_applicable_to_lane', name='verdict'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('assumptions', app.models.domain.JSONType(), nullable=True),
    sa.Column('evidence_items', app.models.domain.JSONType(), nullable=True),
    sa.Column('evidence_refs', app.models.domain.JSONType(), nullable=True),
    sa.Column('provenance_bundle', app.models.domain.JSONType(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'escalated', 'resolved', name='reviewstatus'), nullable=True),
    sa.Column('correlated_verifier_risk', sa.Float(), nullable=True),
    sa.Column('policy_state', sa.Enum('allowed', 'allowed_with_review', 'blocked_pending_exogenous_check', name='policystate'), nullable=True),
    sa.Column('lane_specific_record', app.models.domain.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['learning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('input_refs', app.models.domain.JSONType(), nullable=True),
    sa.Column('output_refs', app.models.domain.JSONType(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='actionstatus'), nullable=True),
    sa.Column('provenance_bundle', app.models.domain.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['learning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('human_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('content_payload', app.models.domain.JSONType(), nullable=False),
    sa.Column('consent_snapshot', app.models.domain.JSONType(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'verified', 'rejected', 'review', 'settled', 'withdrawn', name='contributionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('learning_run_id', sa.String(length=36), nullable=True),
    sa.Column('epistemic_value_proof', app.models.domain.JSONType(), nullable=False),
    sa.Column('viability_proof_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'review', name='settlementstatus'), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=False),
    sa.Column('contributions_settled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_run_id'], ['learning_runs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('human_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('integrity_hash', sa.String(), nullable=False),
    sa.Column('creation_context', app.models.domain.JSONType(), nullable=False),
    sa.Column('transformation_log', app.models.domain.JSONType(), nullable=True),
    sa.Column('withdrawal_status', sa.Enum('submitted', 'verified', 'rejected', 'review', 'settled', 'withdrawn', name='contributionstatus'), nullable=True),
    sa.Column('usage_rights', app.models.domain.JSONType(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['grounding_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_id')
    )
    op.create_table('revocation_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('human_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'completed', 'failed', name='revocationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rollback_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('prior_state_ref', sa.String(), nullable=True),
    sa.Column('rollback_trigger', sa.String(), nullable=True),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action_receipts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['learning_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollback_records')
    op.drop_table('revocation_requests')
    op.drop_table('provenance_records')
    op.drop_table('settlements')
    op.drop_table('contributions')
    op.drop_table('action_receipts')
    op.drop_table('verification_results')
    op.drop_table('review_queue')
    op.drop_table('plans')
    op.drop_table('grounding_requests')
    op.drop_table('consent_profiles')
    op.drop_table('approval_decisions')
    op.drop_table('viability_evaluations')
    op.drop_table('learning_runs')
    op.drop_table('audit_events')
    op.drop_table('actors')
    # ### end Alembic commands ###
