"""add api_keys table for per-agent authentication

Revision ID: c7e2a4f91d05
Revises: a3f8d1c92b47
Create Date: 2026-03-17

Adds a per-agent API key table so that individual agents can authenticate
with scoped keys instead of sharing the single global MAESTRO_API_KEY
environment variable.

Security properties:
  - Only the SHA-256 hex digest of each key is stored (key_hash column).
  - The raw key is generated by the API at creation time and returned once.
  - Revoked keys retain their row (soft delete via revoked_at) for audit
    trail purposes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7e2a4f91d05"
down_revision: Union[str, None] = "a3f8d1c92b47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "agent_id",
            sa.String(36),
            sa.ForeignKey("actors.id"),
            nullable=False,
        ),
        sa.Column("key_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_api_keys_agent_id", "api_keys", ["agent_id"])
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_api_keys_key_hash", table_name="api_keys")
    op.drop_index("ix_api_keys_agent_id", table_name="api_keys")
    op.drop_table("api_keys")
